#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"

[ -s "$HOME/.asdf/asdf.sh" ] && \. $HOME/.asdf/asdf.sh

#############

yarn run lint-staged
